/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "rpc_auth_app.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

reply_authorization *
func_authorization_1(request_authorization arg1,  CLIENT *clnt)
{
	static reply_authorization clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, func_authorization,
		(xdrproc_t) xdr_request_authorization, (caddr_t) &arg1,
		(xdrproc_t) xdr_reply_authorization, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

reply_access_token *
func_access_token_1(request_access_token arg1,  CLIENT *clnt)
{
	static reply_access_token clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, func_access_token,
		(xdrproc_t) xdr_request_access_token, (caddr_t) &arg1,
		(xdrproc_t) xdr_reply_access_token, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

reply_validate_delegated_action *
func_validate_delegated_action_1(request_validate_delegated_action arg1,  CLIENT *clnt)
{
	static reply_validate_delegated_action clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, func_validate_delegated_action,
		(xdrproc_t) xdr_request_validate_delegated_action, (caddr_t) &arg1,
		(xdrproc_t) xdr_reply_validate_delegated_action, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

reply_token_approval *
func_token_approval_1(request_token_approval arg1,  CLIENT *clnt)
{
	static reply_token_approval clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, func_token_approval,
		(xdrproc_t) xdr_request_token_approval, (caddr_t) &arg1,
		(xdrproc_t) xdr_reply_token_approval, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

reply_access_token *
func_renew_access_token_1(request_renew_access_token arg1,  CLIENT *clnt)
{
	static reply_access_token clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, func_renew_access_token,
		(xdrproc_t) xdr_request_renew_access_token, (caddr_t) &arg1,
		(xdrproc_t) xdr_reply_access_token, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
