/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpc_auth_app.h"

bool_t
xdr_request_authorization (XDR *xdrs, request_authorization *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->userID, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_reply_authorization (XDR *xdrs, reply_authorization *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->error_message, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->token_authorize_access, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_request_access_token (XDR *xdrs, request_access_token *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->userID, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->token_authorize_access_signed, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->use_refresh_token))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_reply_access_token (XDR *xdrs, reply_access_token *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->error_message, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->token_resource_access, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->token_refresh, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->validity))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_request_validate_delegated_action (XDR *xdrs, request_validate_delegated_action *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->token_resource_access, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->accessed_resource, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->operation_type, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_reply_validate_delegated_action (XDR *xdrs, reply_validate_delegated_action *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->error_message, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->success_message, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_request_token_approval (XDR *xdrs, request_token_approval *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->token_authorize_access, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_reply_token_approval (XDR *xdrs, reply_token_approval *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->token_authorize_access_signed, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_request_renew_access_token (XDR *xdrs, request_renew_access_token *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->token_resource_access_expired, ~0))
		 return FALSE;
	return TRUE;
}
